# @package _global_

# uses only 1% of the training data and 5% of validation/test data

defaults:
  - default.yaml

trainer:
  max_epochs: 1
  limit_train_batches: 0.001
  limit_val_batches: 0.02
  limit_test_batches: 0.02

# data:
#   data_dir: /Users/lukas/Desktop/projects/MIT/prosody/prosody/repositories/helsinki-prosody/data
